name: Daily Data Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 執行
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run travel.py
        run: python travel.py

      - name: Run exhibition_coming.py
        run: python exhibition_coming.py

      - name: Run exhibition_now.py
        run: python exhibition_now.py

      - name: Run process.py
        run: python process.py

      - name: Process travel.json for frontend
        run: python travel_to_sidejson.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Daily data update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
